site_name: Wagtail Transfer Documentation
theme:
  name: 'material'
  favicon: 'img/wagtail_transfer_logo.svg'
  logo: 'img/wagtail_transfer_logo.svg'
  palette:
    primary: 'teal'
    accent: 'indigo'
markdown_extensions:
  - codehilite
nav:
  - Home: index.md
  - Setup: setup.md
  - Basic Usage: basic_usage.md
  - How It Works: how_it_works.md
  - Management commands: management_commands.md
  - Settings and Hooks: settings.md
